siteTitle = "Blog by Tyler Mcginnis"
siteDescr = "Partner at React Training, Google Developer Expert, Egghead.io Author, React Newsletter Creator."
siteAuthor = "Tyler McGinnis"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/tylermcginnis33"
siteGithubUrl = "https://github.com/tylermcginnis"
siteFacebookUrl="https://www.facebook.com/tylermcginnis.dev"
siteYoutubeUrl="https://www.youtube.com/c/TylerMcGinnis33"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-35670702-1"

linkPrefix = "/"